services:
  mongodb:
    image: mongo
    networks:
      - app-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - db:/data/db

  backend:
    depends_on:
      - mongodb
    image: smolurl-backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}

  frontend:
    depends_on:
      - backend
    networks:
      - app-network
    image: smolurl-frontend
    ports:
      - "4173:4173"


  nginx:
    image: nginx:latest
    ports:
      - "3000:3000" # Expose port 80 to the host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Mount the Nginx config
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db: 